# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otomoto_z_tabelka.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from loading2 import Ui_Form

class Ui_MainWindow(object):
    def open_loading_screen(self):
        print("otwieram loading screen")
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()




    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 729)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_label_i_listy = QtWidgets.QWidget(self.centralwidget)
        self.widget_label_i_listy.setMaximumSize(QtCore.QSize(619, 210))
        self.widget_label_i_listy.setObjectName("widget_label_i_listy")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_label_i_listy)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_label = QtWidgets.QWidget(self.widget_label_i_listy)
        self.widget_label.setMaximumSize(QtCore.QSize(200, 200))
        self.widget_label.setObjectName("widget_label")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_label)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lab_marka = QtWidgets.QLabel(self.widget_label)
        self.lab_marka.setMinimumSize(QtCore.QSize(0, 0))
        self.lab_marka.setMaximumSize(QtCore.QSize(1111111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lab_marka.setFont(font)
        self.lab_marka.setMouseTracking(False)
        self.lab_marka.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_marka.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_marka.setObjectName("lab_marka")
        self.verticalLayout_5.addWidget(self.lab_marka)
        self.lab_model = QtWidgets.QLabel(self.widget_label)
        self.lab_model.setMinimumSize(QtCore.QSize(0, 0))
        self.lab_model.setMaximumSize(QtCore.QSize(1111111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lab_model.setFont(font)
        self.lab_model.setMouseTracking(False)
        self.lab_model.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_model.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_model.setObjectName("lab_model")
        self.verticalLayout_5.addWidget(self.lab_model)
        self.label_rokpr = QtWidgets.QLabel(self.widget_label)
        self.label_rokpr.setMinimumSize(QtCore.QSize(0, 0))
        self.label_rokpr.setMaximumSize(QtCore.QSize(1111111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_rokpr.setFont(font)
        self.label_rokpr.setMouseTracking(False)
        self.label_rokpr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_rokpr.setAutoFillBackground(False)
        self.label_rokpr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rokpr.setObjectName("label_rokpr")
        self.verticalLayout_5.addWidget(self.label_rokpr)
        self.horizontalLayout.addWidget(self.widget_label)
        self.widget_listy = QtWidgets.QWidget(self.widget_label_i_listy)
        self.widget_listy.setMaximumSize(QtCore.QSize(330, 16777215))
        self.widget_listy.setObjectName("widget_listy")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_listy)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.wybor_marka = QtWidgets.QComboBox(self.widget_listy)
        self.wybor_marka.setMinimumSize(QtCore.QSize(0, 30))
        self.wybor_marka.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.wybor_marka.setFont(font)
        self.wybor_marka.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wybor_marka.setFrame(False)
        self.wybor_marka.setObjectName("wybor_marka")
        self.wybor_marka.addItem("")
        self.verticalLayout_4.addWidget(self.wybor_marka)
        self.wybor_model = QtWidgets.QComboBox(self.widget_listy)
        self.wybor_model.setMinimumSize(QtCore.QSize(0, 30))
        self.wybor_model.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.wybor_model.setFont(font)
        self.wybor_model.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wybor_model.setFrame(False)
        self.wybor_model.setObjectName("wybor_model")
        self.wybor_model.addItem("")
        self.verticalLayout_4.addWidget(self.wybor_model)
        self.wybor_rok_produkcji = QtWidgets.QComboBox(self.widget_listy)
        self.wybor_rok_produkcji.setMinimumSize(QtCore.QSize(0, 30))
        self.wybor_rok_produkcji.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.wybor_rok_produkcji.setFont(font)
        self.wybor_rok_produkcji.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wybor_rok_produkcji.setFrame(False)
        self.wybor_rok_produkcji.setObjectName("wybor_rok_produkcji")
        self.wybor_rok_produkcji.addItem("")
        self.verticalLayout_4.addWidget(self.wybor_rok_produkcji)
        self.horizontalLayout.addWidget(self.widget_listy)
        self.verticalLayout.addWidget(self.widget_label_i_listy)
        self.widget_tabelki = QtWidgets.QWidget(self.centralwidget)
        self.widget_tabelki.setMinimumSize(QtCore.QSize(624, 404))
        self.widget_tabelki.setObjectName("widget_tabelki")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_tabelki)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Listaaukcji = QtWidgets.QLabel(self.widget_tabelki)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_Listaaukcji.setFont(font)
        self.label_Listaaukcji.setMouseTracking(False)
        self.label_Listaaukcji.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Listaaukcji.setObjectName("label_Listaaukcji")
        self.verticalLayout_3.addWidget(self.label_Listaaukcji)
        self.tabelka = QtWidgets.QTableWidget(self.widget_tabelki)
        self.tabelka.setMinimumSize(QtCore.QSize(601, 321))
        self.tabelka.setMaximumSize(QtCore.QSize(2000, 2000))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.tabelka.setFont(font)
        self.tabelka.setObjectName("tabelka")
        self.tabelka.setColumnCount(6)
        self.tabelka.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tabelka)
        self.Button_wykres = QtWidgets.QPushButton(self.widget_tabelki)
        self.Button_wykres.setMinimumSize(QtCore.QSize(0, 30))
        self.Button_wykres.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button_wykres.setFont(font)
        self.Button_wykres.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Button_wykres.setObjectName("Button_wykres")
        self.verticalLayout_3.addWidget(self.Button_wykres, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.widget_tabelki)
        self.Button_loading = QtWidgets.QPushButton(self.centralwidget)
        self.Button_loading.setMinimumSize(QtCore.QSize(250, 30))
        self.Button_loading.setMaximumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button_loading.setFont(font)
        self.Button_loading.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Button_loading.setIconSize(QtCore.QSize(5, 5))
        self.Button_loading.setAutoRepeatInterval(0)
        self.Button_loading.setObjectName("Button_loading")

        # connecting button when clicked to function open_loading_screen
        self.Button_loading.clicked.connect(self.open_loading_screen)

        self.verticalLayout.addWidget(self.Button_loading, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action123 = QtWidgets.QAction(MainWindow)
        self.action123.setObjectName("action123")
        self.action123_2 = QtWidgets.QAction(MainWindow)
        self.action123_2.setObjectName("action123_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_marka.setText(_translate("MainWindow", "Marka"))
        self.lab_model.setText(_translate("MainWindow", "Model"))
        self.label_rokpr.setText(_translate("MainWindow", "rok produkcji"))
        self.wybor_marka.setItemText(0, _translate("MainWindow", "Opel"))
        self.wybor_model.setItemText(0, _translate("MainWindow", "Corsa"))
        self.wybor_rok_produkcji.setItemText(0, _translate("MainWindow", "2020"))
        self.label_Listaaukcji.setText(_translate("MainWindow", "Lista aukcji"))
        item = self.tabelka.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Marka"))
        item = self.tabelka.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.tabelka.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "cena"))
        item = self.tabelka.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "rok produkcji"))
        item = self.tabelka.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "przebieg"))
        item = self.tabelka.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "link"))
        self.Button_wykres.setText(_translate("MainWindow", "Wykres Danych"))

        self.Button_loading.setText(_translate("MainWindow", "Aktualizuj bazę danych"))


        self.action123.setText(_translate("MainWindow", "123"))
        self.action123_2.setText(_translate("MainWindow", "123"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
