from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure
import sys
import modele
import random
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
import PyQt5.Qt
import webbrowser


class Ui_MainWindow():
    def __init__(self):

        app = QtWidgets.QApplication(sys.argv)
        app.setWindowIcon(QtGui.QIcon("ikonka.png"))
        MainWindow = QtWidgets.QMainWindow()
        # ustawienie wszystkich elementów
        self.setupUi(MainWindow)
        MainWindow.resize(600,780)
        MainWindow.show()
        sys.exit(app.exec_())

    def button1clicked(self):
        print("klinknieto")
        marka = self.wybor_marka.currentText()
        model = self.wybor_model.currentText()
        rok = self.wybor_rok_produkcji.currentText()
        self.ustawienia_tabelki()
        plt = modele.Wykresik("20.03.2020.db", marka, model, rok)
        plt.show()

    def funkcja(self):
        print("otwórz stronę")
        wiersz = self.tabelka.currentRow()
        kolumna = self.tabelka.currentColumn()
        if (kolumna == 5):
            # print(self.tabelka.item(wiersz,kolumna).text())
            webbrowser.open(self.tabelka.item(wiersz, kolumna).text())

    def ustawienia_tabelki(self):
        print("USTAWIENIA TABELKI")
        marka = self.wybor_marka.currentText()
        model = self.wybor_model.currentText()
        rok = self.wybor_rok_produkcji.currentText()
        dane = modele.dane_lista("20.03.2020.db", marka, model, rok)

        self.tabelka.setRowCount(len(dane))


        item = QtWidgets.QTableWidgetItem()
        item.setData(PyQt5.QtCore.Qt.DisplayRole, 6)
        print(type(item))


        for d in range(len(dane)):
            self.tabelka.setItem(d, 0, QtWidgets.QTableWidgetItem(dane[d][0]))
            self.tabelka.setItem(d, 1, QtWidgets.QTableWidgetItem(dane[d][1]))
            cena = QtWidgets.QTableWidgetItem()
            cena.setData(PyQt5.QtCore.Qt.DisplayRole, dane[d][2])
            self.tabelka.setItem(d, 2, cena)
            self.tabelka.setItem(d, 3, QtWidgets.QTableWidgetItem(str(dane[d][3])))
            self.tabelka.setItem(d, 4, QtWidgets.QTableWidgetItem(str(dane[d][4]) + " km"))
            self.tabelka.setItem(d, 5, QtWidgets.QTableWidgetItem(str(dane[d][7])))
        self.tabelka.cellDoubleClicked.connect(self.funkcja)
        self.tabelka.setSortingEnabled(True)
        #self.tabelka.cellDoubleClicked.connect(self.funkcja)

    def update_model_list(self):
        self.wybor_model.clear()
        f = open("marki.txt", "r")
        for i, line in enumerate(f):
            if (i == self.wybor_marka.currentIndex()-1):
                self.wybor_model.addItems(line.split(","))

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 766)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_label_i_listy = QtWidgets.QWidget(self.centralwidget)
        self.widget_label_i_listy.setMaximumSize(QtCore.QSize(619, 210))
        self.widget_label_i_listy.setObjectName("widget_label_i_listy")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_label_i_listy)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_label = QtWidgets.QWidget(self.widget_label_i_listy)
        self.widget_label.setMaximumSize(QtCore.QSize(200, 200))
        self.widget_label.setObjectName("widget_label")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_label)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lab_marka = QtWidgets.QLabel(self.widget_label)
        self.lab_marka.setMinimumSize(QtCore.QSize(0, 0))
        self.lab_marka.setMaximumSize(QtCore.QSize(1111111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lab_marka.setFont(font)
        self.lab_marka.setMouseTracking(False)
        self.lab_marka.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_marka.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_marka.setObjectName("lab_marka")
        self.verticalLayout_5.addWidget(self.lab_marka)
        self.lab_model = QtWidgets.QLabel(self.widget_label)
        self.lab_model.setMinimumSize(QtCore.QSize(0, 0))
        self.lab_model.setMaximumSize(QtCore.QSize(1111111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lab_model.setFont(font)
        self.lab_model.setMouseTracking(False)
        self.lab_model.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_model.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_model.setObjectName("lab_model")
        self.verticalLayout_5.addWidget(self.lab_model)
        self.label_rokpr = QtWidgets.QLabel(self.widget_label)
        self.label_rokpr.setMinimumSize(QtCore.QSize(0, 0))
        self.label_rokpr.setMaximumSize(QtCore.QSize(1111111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_rokpr.setFont(font)
        self.label_rokpr.setMouseTracking(False)
        self.label_rokpr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_rokpr.setAutoFillBackground(False)
        self.label_rokpr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rokpr.setObjectName("label_rokpr")
        self.verticalLayout_5.addWidget(self.label_rokpr)
        self.label_przegiegod = QtWidgets.QLabel(self.widget_label)
        self.label_przegiegod.setMinimumSize(QtCore.QSize(0, 0))
        self.label_przegiegod.setMaximumSize(QtCore.QSize(1111111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_przegiegod.setFont(font)
        self.label_przegiegod.setMouseTracking(False)
        self.label_przegiegod.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_przegiegod.setAutoFillBackground(False)
        self.label_przegiegod.setAlignment(QtCore.Qt.AlignCenter)
        self.label_przegiegod.setObjectName("label_przegiegod")
        self.verticalLayout_5.addWidget(self.label_przegiegod)
        self.label_przegiegdo = QtWidgets.QLabel(self.widget_label)
        self.label_przegiegdo.setMinimumSize(QtCore.QSize(0, 0))
        self.label_przegiegdo.setMaximumSize(QtCore.QSize(1111111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_przegiegdo.setFont(font)
        self.label_przegiegdo.setMouseTracking(False)
        self.label_przegiegdo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_przegiegdo.setAutoFillBackground(False)
        self.label_przegiegdo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_przegiegdo.setObjectName("label_przegiegdo")
        self.verticalLayout_5.addWidget(self.label_przegiegdo)
        self.horizontalLayout.addWidget(self.widget_label)
        self.widget_listy = QtWidgets.QWidget(self.widget_label_i_listy)
        self.widget_listy.setMaximumSize(QtCore.QSize(330, 16777215))
        self.widget_listy.setObjectName("widget_listy")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_listy)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.wybor_marka = QtWidgets.QComboBox(self.widget_listy)
        self.wybor_marka.setMinimumSize(QtCore.QSize(0, 30))
        self.wybor_marka.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.wybor_marka.setFont(font)
        self.wybor_marka.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wybor_marka.setFrame(False)
        self.wybor_marka.setObjectName("wybor_marka")
        self.wybor_marka.addItem("")
        self.verticalLayout_4.addWidget(self.wybor_marka)
        self.wybor_model = QtWidgets.QComboBox(self.widget_listy)
        self.wybor_model.setMinimumSize(QtCore.QSize(0, 30))
        self.wybor_model.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.wybor_model.setFont(font)
        self.wybor_model.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wybor_model.setFrame(False)
        self.wybor_model.setObjectName("wybor_model")
        self.verticalLayout_4.addWidget(self.wybor_model)
        self.wybor_rok_produkcji = QtWidgets.QComboBox(self.widget_listy)
        self.wybor_rok_produkcji.setMinimumSize(QtCore.QSize(0, 30))
        self.wybor_rok_produkcji.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.wybor_rok_produkcji.setFont(font)
        self.wybor_rok_produkcji.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wybor_rok_produkcji.setFrame(False)
        self.wybor_rok_produkcji.setObjectName("wybor_rok_produkcji")
        self.verticalLayout_4.addWidget(self.wybor_rok_produkcji)
        self.wybor_przebiegod = QtWidgets.QDoubleSpinBox(self.widget_listy)
        self.wybor_przebiegod.setMinimumSize(QtCore.QSize(0, 30))
        self.wybor_przebiegod.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.wybor_przebiegod.setFont(font)
        self.wybor_przebiegod.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wybor_przebiegod.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.wybor_przebiegod.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.wybor_przebiegod.setDecimals(0)
        self.wybor_przebiegod.setMaximum(100000.0)
        self.wybor_przebiegod.setSingleStep(5000.0)
        self.wybor_przebiegod.setProperty("value", 0.0)
        self.wybor_przebiegod.setObjectName("wybor_przebiegod")
        self.verticalLayout_4.addWidget(self.wybor_przebiegod)
        self.wybor_przebiegdo = QtWidgets.QDoubleSpinBox(self.widget_listy)
        self.wybor_przebiegdo.setMinimumSize(QtCore.QSize(0, 30))
        self.wybor_przebiegdo.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.wybor_przebiegdo.setFont(font)
        self.wybor_przebiegdo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wybor_przebiegdo.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.wybor_przebiegdo.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.wybor_przebiegdo.setDecimals(0)
        self.wybor_przebiegdo.setMaximum(100000.0)
        self.wybor_przebiegdo.setSingleStep(5000.0)
        self.wybor_przebiegdo.setProperty("value", 0.0)
        self.wybor_przebiegdo.setObjectName("wybor_przebiegdo")
        self.verticalLayout_4.addWidget(self.wybor_przebiegdo)
        self.horizontalLayout.addWidget(self.widget_listy)
        self.verticalLayout.addWidget(self.widget_label_i_listy)
        self.widget_tabelki = QtWidgets.QWidget(self.centralwidget)
        self.widget_tabelki.setMinimumSize(QtCore.QSize(624, 404))
        self.widget_tabelki.setObjectName("widget_tabelki")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_tabelki)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Listaaukcji = QtWidgets.QLabel(self.widget_tabelki)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_Listaaukcji.setFont(font)
        self.label_Listaaukcji.setMouseTracking(False)
        self.label_Listaaukcji.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Listaaukcji.setObjectName("label_Listaaukcji")
        self.verticalLayout_3.addWidget(self.label_Listaaukcji)
        self.tabelka = QtWidgets.QTableWidget(self.widget_tabelki)
        self.tabelka.setMinimumSize(QtCore.QSize(601, 321))
        self.tabelka.setMaximumSize(QtCore.QSize(2000, 2000))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.tabelka.setFont(font)
        self.tabelka.setObjectName("tabelka")
        self.tabelka.setColumnCount(6)
        self.tabelka.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelka.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tabelka)
        self.Button_wykres = QtWidgets.QPushButton(self.widget_tabelki)
        self.Button_wykres.setMinimumSize(QtCore.QSize(0, 30))
        self.Button_wykres.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button_wykres.setFont(font)
        self.Button_wykres.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Button_wykres.setObjectName("Button_wykres")
        self.verticalLayout_3.addWidget(self.Button_wykres, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.widget_tabelki)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 652, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



        # wczytanie marek pojazdów
        file = open("marki.txt", "r")
        f = open("marki.txt", "r")
        for i in f.readlines():
            self.wybor_marka.addItem(i.split(",")[0])

        self.wybor_rok_produkcji.addItem("")
        for i in range(40):
            rok = 2020 - i
            self.wybor_rok_produkcji.addItem(str(rok))

        self.tabelka.setColumnCount(6)
        self.tabelka.setRowCount(12)

        self.Button_wykres.clicked.connect(self.button1clicked)
        #self.wybor_marka.currentTextChanged(self.update_model_list)
        self.wybor_marka.currentTextChanged.connect(self.update_model_list, self.wybor_marka.currentIndex())
        self.wybor_model.currentTextChanged.connect(self.ustawienia_tabelki,self.wybor_model.currentIndex())
        self.wybor_rok_produkcji.currentTextChanged.connect(self.ustawienia_tabelki, self.wybor_rok_produkcji.currentIndex())

    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "Samochody to mój świat"))
        self.lab_marka.setText(_translate("MainWindow", "Marka"))
        self.lab_model.setText(_translate("MainWindow", "Model"))
        self.label_rokpr.setText(_translate("MainWindow", "rok produkcji"))
        self.label_przegiegod.setText(_translate("MainWindow", "przebieg od"))
        self.label_przegiegdo.setText(_translate("MainWindow", "przebieg do"))
        self.wybor_przebiegod.setSuffix(_translate("MainWindow", " KM"))
        self.wybor_przebiegdo.setSuffix(_translate("MainWindow", " KM"))
        self.label_Listaaukcji.setText(_translate("MainWindow", "Lista aukcji"))
        item = self.tabelka.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Marka"))
        item = self.tabelka.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.tabelka.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "cena"))
        item = self.tabelka.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "rok produkcji"))
        item = self.tabelka.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "przebieg"))
        item = self.tabelka.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "link"))
        self.Button_wykres.setText(_translate("MainWindow", "Wykres Danych"))


Ui_MainWindow()